### ISSUE TITLE
Please, update the plugin!..

### ISSUE THREAD

**Issue by swordin** [lenis0012/LoginSecurity-2#100]
Please, when will you update the plugin???

We're waiting for fix:

(1) A problem in uppercase and lowercase letters of the nics! (issue #85) — the hacker may enters the server with wrong nick!
(2) A problem with /reg and /l commands! — we’re losing new players
(3) A problem with /rmpass command! (issue #87) — errors

Best regards!

**Comment by Tzzzt123** [comment]
@lenis0012 why no answer?
PLS ANSWER

**Comment by Tzzzt123** [comment]
I msged him on Bukkitdev and Spigotmc.org today, I may get an answer in the next few days.
Thanks for waiting @swordin

**Comment by swordin** [comment]
Thnx a lot! )

**Comment by lenis0012** [comment]
@swordin @Tzzzt123 Can't give you guys an exact date, but I am going to do it as soon as I have time.
Which will probably be very soon.

Thanks for showing your interest, it definitely makes me more excited to work on it.

**Comment by swordin** [comment]
Thank you very much! Спасибище! )

**Comment by Tzzzt123** [comment]
Thanks alot @lenis0012

**Comment by lenis0012** [comment]
@swordin @Tzzzt123 https://github.com/lenis0012/LoginSecurity-2/commit/b9a43407f6be61fc43bb1b954dc8c68576503f26

its in progress

**Comment by Tzzzt123** [comment]
btw @lenis0012 did you read my msgs on Spigotmc and bukkitdev?

**Comment by lenis0012** [comment]
@Tzzzt123 Not yet. I am at work right now but ill check it when i get home

**Comment by Tzzzt123** [comment]
@lenis0012 ok

**Comment by lenis0012** [comment]
@Tzzzt123 @swordin Lot's of progress today.
I'm almost done switching out the database engine, which is around 75% of the work for this update.

**Comment by swordin** [comment]
Cool! )

**Comment by Tzzzt123** [comment]
@lenis0012 NICE

**Comment by swordin** [comment]
The audience froze in anticipation... )

**Comment by Tzzzt123** [comment]
yep @swordin 
@lenis0012 will we have to do /lac dbimport Legacy2.1 next time or will it auto-inport?
Thanks for answering
@Tzzzt123

**Comment by lenis0012** [comment]
@Tzzzt123 LoginSecurity 2.2 uses the same data format as version 2.1.
There is no need for any conversion/importing.

**Comment by Tzzzt123** [comment]
Good.

**Comment by swordin** [comment]
Praise God! )

**Comment by swordin** [comment]
Please...

**Comment by lenis0012** [comment]
@swordin Work has been happening behind the scenes.
I won't disappoint =)

**Comment by swordin** [comment]
And that is great! I will update it today!

**Comment by swordin** [comment]
Hello, the problem with /l is not fixed:

>  (2) A problem with /reg and /l commands! — we’re losing new players

The rest things I did not check.

**Comment by swordin** [comment]
explanation: as it was earlier - when I enters with /l <password> it says: "wrong password"

**Comment by swordin** [comment]
Moreover, several players could not enter - the password did not match ((( 

So I had to roll back the base, reset the passwords to these players and re-install 2.1.6 back (

**Comment by swordin** [comment]
Regarding wrong passwords - it's my mistake. Sorry )

But the problem with /l (and, perhaps, /reg) - the problem is actual.

**Comment by lenis0012** [comment]
@swordin Yes, this issue is only fixed in the in-development 2.2.0 version.
I did not backport it to 2.1.7

**Comment by lenis0012** [comment]
@swordin Version 2.1.7 is the same as 2.1.6 except that it is compatible with minecraft 1.12

**Comment by swordin** [comment]
As I can see - not 1.12, but 1.8:

http://shpagin.ru/enigmaproject/217.png

**Comment by lenis0012** [comment]
@swordin 1.12 wasn't in the selection menu.
It supports 1.8, 1.9, 1.10, 1.11 and 1.12

**Comment by swordin** [comment]
Ok. Anyway, we're waiting the version which corrects the bugs.

**Comment by swordin** [comment]
PLEASE UPDATE TO 2.2

we can't wait fix errors anymore
