### ISSUE TITLE
Re-add /lac changepass

### ISSUE THREAD

**Issue by Tzzzt123** [lenis0012/LoginSecurity-2#104]
Thanks for answering

**Comment by lenis0012** [comment]
https://github.com/lenis0012/LoginSecurity-2/milestone/1 @Tzzzt123

**Comment by Tzzzt123** [comment]
@lenis0012 i watched the code and i didn't find something like /lac changepass

**Comment by Tzzzt123** [comment]
@lenis0012 ?
