### ISSUE TITLE
2.1.6 to 2.17 import - what am I doing wrong?

### ISSUE THREAD

**Issue by Shiikii** [lenis0012/LoginSecurity-2#109]
Hi!

I updated spigot server from 1.11 to 1.12, so I updated also Login Security. I dropped 2.1.7 file into plugins directory, and this happend 
https://hastebin.com/xuboyamajo

Players need to register again, like old DB never existed...

**Comment by lenis0012** [comment]
The log you provided is not an error.
if your players need to register again there is another issue at hand.

Are you sure everyone has to register again?

**Comment by lenis0012** [comment]
LoginSecurity never deletes user accounts, even on a migration.
So they can't simply disappear

**Comment by Shiikii** [comment]
I provided everything about Login Security from console .

Reason of no accounts was corrupted *.db (file size was half of original), now everything seems to work, sorry for troubling you.

**Comment by lenis0012** [comment]
@Shiikii No problem.
I am glad that you were able to resolve your issue.
