### ISSUE TITLE
Maven repository empty

### ISSUE THREAD

**Issue by games647** [lenis0012/LoginSecurity-2#114]
Your Maven repository is empty. It contains no artifact. Could you fix it please?

**Comment by lenis0012** [comment]
@games647 Probably happened when I moved the server.
It seems that the repository was not included in the backup.

I will fix it when I get home.

**Comment by games647** [comment]
Thank you very much.

**Comment by lenis0012** [comment]
@games647 v2.1.7 is on the repository.
http://ci.lenis0012.com/plugin/repository/everything/com/lenis0012/bukkit/loginsecurity/2.1.7/
