### ISSUE TITLE
REGister problem

### ISSUE THREAD

**Issue by Narkoo** [lenis0012/LoginSecurity-2#116]
Hello, can you update ls to 1.12?
I use LoginSecurity, but new members cant use / reg, only /register.
Yes, i set "shortcut command", /l works
/reg wrote: your password must be 4-32 symbols, I try 4,5,6,10 symbols, but the result does not change
I try to remove all other plugins :(

**Comment by lenis0012** [comment]
This is related to #119 and should be fixed.
