### ISSUE TITLE
Registering from PHP script

### ISSUE THREAD

**Issue by franceja** [lenis0012/LoginSecurity-2#131]
I want to make people can login from web and register from web which I have tried to make one, but when you register from web you can not login with the one which you registered from web.

Here is my code : 
```php
function TempoRegisterForNewPlugin($username,$password){
        require_once 'uuid.php';
        $uuid = constructOfflinePlayerUuid($username);
        $HashPassword = password_hash($password,PASSWORD_BCRYPT);
        $date = date("Y-m-d H:i:s"); 
        $sql = "INSERT INTO ls_players (unique_user_id,last_name,ip_address,password,hashing_algorithm,registration_date,uuid_mode,optlock) 
        VALUES ('".$uuid."','".$username."','".'127.0.0.1'."','".$HashPassword."','".'7'."','".$date."','O','1')";
        $query = connection_msql($sql,'bbf');
        return 'TRUE';
    }
```

I quite sure that my password constructor is wrong, Please help me about this I want to integrate these with my own website.

P.S. I used https://gist.github.com/games647/2b6a00a8fc21fd3b88375f03c9e2e603 to make uuid.

**Comment by franceja** [comment]
This issues is fixed !!

**Comment by franceja** [comment]
This issues is fixed !!

**Comment by lenis0012** [comment]
@franceja Im glad you figured it out
