### ISSUE TITLE
Can`t download latest version.

### ISSUE THREAD

**Issue by baxandrei** [lenis0012/LoginSecurity-2#133]
http://ci.lenis0012.com/job/LoginSecurity/12/artifact/target/LoginSecurity-2.1.8-Spigot.jar :
502 Bad Gateway
nginx/1.10.3

**Comment by xXxAaRkEtxXx** [comment]
oof he ded

**Comment by baxandrei** [comment]
[LoginSecurity.zip](https://github.com/lenis0012/LoginSecurity-2/files/2973785/LoginSecurity.zip)

**Comment by lenis0012** [comment]
@xXxAaRkEtxXx @baxandrei A new update is available, and hosted on github, so it probably won't happen again.
