### ISSUE TITLE
Spamming bug

### ISSUE THREAD

**Issue by legend10X** [lenis0012/LoginSecurity-2#135]
I got this spamming messages when i have it on but the plugin still works but its spamming the crap out of the console and i cant figure out how to fix this need help(i tried it on 2.1.8 but its the same)

Screenshot:

https://user-images.githubusercontent.com/50336646/57243105-d93b5f00-7067-11e9-8d78-60aae8a11ea9.png

**Comment by lenis0012** [comment]
does this always occur, or only after doing a specific thing or asfter a specific amount of time?
I am assuming it persists after restarts.
Did you by chance use the /reload command? It is know to give issues with LoginSecurity.
Are you using other non-standard plugins/tools (bungeecord, PerWorldPlugins, etc)?

**Comment by legend10X** [comment]
It always doing it everytime i start the server,i did not use the /reload command,nopey

**Comment by lenis0012** [comment]
I will see if I can reproduce this issue. I can't really explain it from the error though.

**Comment by lenis0012** [comment]
Actually, do you happen to use an NPC plugin?
@legend10X

**Comment by legend10X** [comment]
I dont use  npc plugin but i have fakeplayers plygin but i havent used it

**Comment by legend10X** [comment]
Well yes fakeplayers count as an npc😅

**Comment by legend10X** [comment]
I havent spawned any fakeplayers yet but how do i prevent this plugin to spam me ?

**Comment by lenis0012** [comment]
@legend10X If you can, temporarily uninstall fakeplayers.
I will fix this error in the next version.
