### ISSUE TITLE
Database Init Problem

### ISSUE THREAD

**Issue by Leohige** [lenis0012/LoginSecurity-2#142]
I'm trying to install the plugin using mysql and i'm getting this error:

``com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key len
gth is 767 bytes``

It's a clean server and database

**Comment by lenis0012** [comment]
Could you provide a little more information?

When did this occur (during startup, login or some command)?
Is this the full error?
What version of LoginSecurity and Spigot are you using?

**Comment by Leohige** [comment]
That's the full error, it occurs in startup when MySQL connection is set and tables are created.

I'm using paper 1.3.2 build 627 and LoginSecurity 3.0.0

I fixed this by changing this command when a I create the database.

``SQL
CREATE DATABASE <DATABASE_NAME> CHARACTER SET latin1;
``

**Comment by lenis0012** [comment]
@Leohige I see.
This issue appears to be related to using an old version of mysql and using a non-standard character set.

If you are using the UTF8 character set or latin1, you should be fine.
Keep in mind that latin1 does not support non-standard characters.

This is not something I can fix in my plugin unfortunately.

**Comment by Leohige** [comment]
I'm trying to use UTF8 but it doesnt work and I'm using the latest version of MariaDB

**Comment by ljacqu** [comment]
I think it depends on the database engine that MySQL uses. If you create an index over columns that take up more than 767 bytes that one engine complains. 
On mobile & abroad so can‘t look up much, but I think it‘s InnoDB that creates problems, _or_ choosing it fixes it :)
