### ISSUE TITLE
/lac rmpass not working

### ISSUE THREAD

**Issue by jomo** [lenis0012/LoginSecurity-2#15]
`/lac rmpass` always returns "Invalid username"
I think this is because you've swapped the true/false part in [this line](https://github.com/lenis0012/LoginSecurity-2/blob/45e5d27c2ef889e48ab75d7ca5b8a6542841e0e7/src/main/java/com/lenis0012/bukkit/ls/commands/AdminCommand.java#L32).

**Comment by lenis0012** [comment]
Fixed
