### ISSUE TITLE
Players losing all their items

### ISSUE THREAD

**Issue by martinstrotbek** [lenis0012/LoginSecurity-2#155]
Currently using LoginSecurity-3.0.1-Spigot, when players quit the game and get back in, if the game auto logs them in, they log in into empty inventories
I managed to replicate this error, type /logout then /login again and it fixed it for me, but others claim that they lost them anyways after doing that, and even losing them using /logout before quitting
other plugins:

EasyPermissionsEx
PermissionEx
WarpsGUI

**Comment by baxandrei** [comment]
My players have same problem.

**Comment by DjGamerDz** [comment]
Same here, i think disabling hide inventory will stop that

**Comment by samolego** [comment]
Check out #146

**Comment by alessandrosimonelli** [comment]
I'm having the same issue, thx to @samolego for the temp fix!

**Comment by NoniDOTio** [comment]
Has someone figured out how to restore a lost inventory? I got multiple backups of my LoginSecurity database but I'm unable to match an inventory tuple to a specific player.

**Comment by errcodex** [comment]
What is even more terrible is that on my server, if you have not noticed that the items disappeared, and any items are picked up, all the items will be lost and unrecoverable.

**Comment by errcodex** [comment]
Even more terrible is that on my server, if you have not noticed that the items disappeared, and you pick up any items, all the items will be lost and unrecoverable.

**Comment by Hakej** [comment]
Happened to my girlfriend too.
