### ISSUE TITLE
Login impossble from inside a Nether Portal

### ISSUE THREAD

**Issue by KaseiFR** [lenis0012/LoginSecurity-2#16]
Hello,
I got disconnected while I was teleporting via a Nather Portal, and since you cannot use the chat in the same time, I got stuck without being able to log in.
And with #15, I couldn't even reset authentification. I had to login and tp myself away with admin command.

Could you allow login from inside Nether Portals? Or automatically teleport the player away while login, and then teleport it back on success?

**Comment by 6minguez** [comment]
hi lenis0012
I have the same problem.
But using fake location I can login but then I die.
If you need more info about the problem I can help you.

**Comment by lenis0012** [comment]
Please report if present in 2.1
