### ISSUE TITLE
AuthActionEvent may only be triggered asynchronously.

### ISSUE THREAD

**Issue by TheProgramSrc** [lenis0012/LoginSecurity-2#166]
I got this error: https://hastebin.com/qugepujika.apache

**Comment by TheProgramSrc** [comment]
Also I got this in the console `05.12 16:15:57 [Server] INFO TheProgramSrc issued server command: /login test`

**Comment by TheProgramSrc** [comment]
How can I disable that?

**Comment by lenis0012** [comment]
This issue seems related to FastLogin.

Have you resolved the issue? @TheProgramSrc

**Comment by TheProgramSrc** [comment]
Yes

Enviado desde Apple Mail
— Francisco
