### ISSUE TITLE
Error fetching languages

### ISSUE THREAD

**Issue by creptor** [lenis0012/LoginSecurity-2#172]
On start this plugin gives an error when fetching the spanish language.

[Console output.](https://pastebin.com/MLvVaCMq)

Basically the server is not responding appropriately and I'm wondering if it can be upload manually.

**Comment by lenis0012** [comment]
@creptor I fixed the issue. Apologies for taking 3 days.

**Comment by creptor** [comment]
Thanks for the support!! :D
