### ISSUE TITLE
Languages Died

### ISSUE THREAD

**Issue by RisDN** [lenis0012/LoginSecurity-2#176]
**When enabling the plugin, i get this error. Even if you go to the http://lang.lenis0012.com/language/hu_hu site it says bad gateway. Please fix this issue fast as possible!!!** 

26.04 21:08:24 [Server] INFO RisDoesNothing issued server command: /plugman reload LoginSecurity
26.04 21:08:24 [Server] INFO [LoginSecurity] Disabling LoginSecurity v3.0.1
26.04 21:08:24 [Server] INFO [LoginSecurity] Waiting for queued tasks...
26.04 21:08:24 [Server] INFO [LoginSecurity] ExecutorService shut down, ready to disable.
26.04 21:08:27 [Server] WARN Legacy plugin LoginSecurity v3.0.1 does not specify an api-version.
26.04 21:08:27 [Server] INFO [LoginSecurity] Enabling LoginSecurity v3.0.1*
26.04 21:08:27 [Server] INFO [LoginSecurity] Loading base translations from "en_us"
26.04 21:08:27 [Server] INFO [LoginSecurity] Loading specified translations from "hu_hu"
26.04 21:08:27 [Server] WARN [LoginSecurity] Couldn't get translation, defaulting to en_us
26.04 21:08:27 [Server] INFO java.io.IOException: Server returned HTTP response code: 502 for URL: http://lang.lenis0012.com/language/hu_hu
26.04 21:08:27 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900) ~[?:1.8.0_242]
26.04 21:08:27 [Server] INFO at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_242]
26.04 21:08:27 [Server] INFO at com.lenis0012.bukkit.loginsecurity.modules.language.LanguageAPI.apiRequest(LanguageAPI.java:61) ~[?:?]
26.04 21:08:27 [Server] INFO at com.lenis0012.bukkit.loginsecurity.modules.language.LanguageAPI.getTranslation(LanguageAPI.java:47) ~[?:?]
26.04 21:08:27 [Server] INFO at com.lenis0012.bukkit.loginsecurity.modules.language.LanguageModule.enable(LanguageModule.java:34) ~[?:?]
26.04 21:08:27 [Server] INFO at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModule(Registry.java:88) ~[?:?]
26.04 21:08:27 [Server] INFO at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.Registry.enableModules(Registry.java:58) ~[?:?]
26.04 21:08:27 [Server] INFO at com.lenis0012.bukkit.loginsecurity.libs.pluginutils.PluginHolder.onEnable(PluginHolder.java:28) ~[?:?]
26.04 21:08:27 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) ~[?:?]
26.04 21:08:27 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318) ~[?:?]
26.04 21:08:27 [Server] INFO at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380) ~[?:?]
26.04 21:08:27 [Server] INFO at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122) ~[?:?]
26.04 21:08:27 [Server] INFO at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) ~[?:?]
26.04 21:08:27 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1825) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1633) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-162]
26.04 21:08:27 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

**Comment by lenis0012** [comment]
Permanently fixed in version 3.0.2 coming out today
