### ISSUE TITLE
Problem with the new translation system

### ISSUE THREAD

**Issue by Shezitt** [lenis0012/LoginSecurity-2#178]
Hello, I take this opportunity to congratulate you on the work that has been done with this plugin and I appreciate that a new update has been released recently.
I have a problem with new translations, I am talking about translations to "es_mx", as you already know, Spanish has special characters, because of that, with the new translation system, special characters are loading me wrong. With the previous system it was fine, it loaded correctly. I don't know why this is or maybe I'm doing something wrong. Thanks in advance.
Next, I leave an image of what I mean: 

WITH 2.1.9: https://i.imgur.com/Z2KrJa5.png 
NOW: https://i.imgur.com/hZef9wD.png

The solution that I use is to use the previous version (2.1.9).

**Comment by lenis0012** [comment]
Can you test https://ci.codemc.io/job/lenis0012/job/LoginSecurity/59/ ?

**Comment by Shezitt** [comment]
> ¿Puedes probar https://ci.codemc.io/job/lenis0012/job/LoginSecurity/59/ ?

Perfect, now it works fine. Good job, thank you very much!
