### ISSUE TITLE
LoginSecurity clears user inventory

### ISSUE THREAD

**Issue by Cyberyisus2g** [lenis0012/LoginSecurity-2#179]
Sometimes, if a player is lagging, the plugin doesn't give his inventory back at login (I have the Hide inventory enabled)

And sometimes, the plugin doesn't teleport the player back where they logged off

Sorry if my english is not good.

**Comment by Axer22** [comment]
Happening to me too.

**Comment by lenis0012** [comment]
Inventory hiding is being improved in the version 3.1, I recommend that any players experiencing issues disable inventory hiding in the config.
