### ISSUE TITLE
Move from DB File to mysql

### ISSUE THREAD

**Issue by fastayko** [lenis0012/LoginSecurity-2#181]
Hello, 

I started using mysql and i want to move the db file to the mysql so my plugin can use it, is there anyway for that? and also how to make the plugin detect that player logged in successfully ?

**Comment by lenis0012** [comment]
1. Stop server
2. Edit database settings with your mysql settings
3. Enable white-list so no one can log on during the conversion process
4. Start server and run in console: lac import loginsecurity
5. When done, stop server, disable whitelist and restart.
