### ISSUE TITLE
Translation "ru_RU" not working at LoginSecurity 3.0.1

### ISSUE THREAD

**Issue by nnrootnsk** [lenis0012/LoginSecurity-2#183]
Hi, I had a problem installing the language in the LoginSecurity configuration file, after I indicated the name "ru_ru", nothing changed, and the plugin complained about the lack of this language. I will ask you to respond.

Using a Paper 1.14.4
([LoginSecurity] Can't find translation for ru_ru. Are you upt to date?)

**Comment by lenis0012** [comment]
Please use the latest dev build: https://ci.codemc.io/job/lenis0012/job/LoginSecurity/

Create a new issue if you are still experiencing issues.
