### ISSUE TITLE
Not Blocking Block Touch Event

### ISSUE THREAD

**Issue by DefinitlyEvil** [lenis0012/LoginSecurity-2#19]
Not Blocking Block Touch Event.

**Comment by lenis0012** [comment]
Please report if present in 2.1

**Comment by DefinitlyEvil** [comment]
Nice to see this fixed. xD

**Comment by lenis0012** [comment]
@DefinitlyEvil Not sure if its fixed.
Please test in 2.1 and open new issue if it still happens.

If it does, ill fix it immediately

**Comment by DefinitlyEvil** [comment]
@lenis0012 Okay, I will post things here if any errors occurs.
