### ISSUE TITLE
Username no UUID?

### ISSUE THREAD

**Issue by Optigonnn** [lenis0012/LoginSecurity-2#20]
Hello,

is it possible you could develop a version that does not use UUID but rather just a username for offline-mode users since UUID creates errors etc.

Thanks.

**Comment by TheEVIL** [comment]
I no have errors.. but i want too no uuids :D

**Comment by lenis0012** [comment]
UUIDS are generated based on player names in offline mode.
There is no point in using names since the data files are not meant to be read by anyone, their only purpose is storage

**Comment by Vilican** [comment]
I quite agree with this ticket. Names allow me to use same logins on the server website (SSO).

**Comment by lenis0012** [comment]
Ill think about it

**Comment by lenis0012** [comment]
LoginSecurity 2.1 will store player names in the database
