### ISSUE TITLE
Players Inventory Disappear 

### ISSUE THREAD

**Issue by Audiozz** [lenis0012/LoginSecurity-2#209]
When my friends disconnect and rejoin sometimes his inventory just disappears sometimes rejoining brings back the inventory.. but most of the time Its not, which cause us lose of items which is really frustrating ...

**Comment by Vulcankta** [comment]
Bad luck. I'm having the same problem.

**Comment by icanotc** [comment]
same problem here, some times it works, sometimes it doesn't, haven't checked the uuid, need some testing to done

**Comment by malpkakefirek** [comment]
disabling hiding items for not logged in players fixed the problem for me
