### ISSUE TITLE
Players Inventory Disappear

### ISSUE THREAD

**Issue by assasinos** [lenis0012/LoginSecurity-2#218]
My friend disconnected and rejoin all of his items were gone.

**Comment by Unknown0229** [comment]
Yes, tell him to reconnect and it should get fixed but yeah it's a bug with 1.16

**Comment by malpkakefirek** [comment]
I had the same problem on my server, but there were a couple times the items didn't reappear after reconnecting. Disabling hiding items while not logged in fixed the problem though.

**Comment by ThePilotNinja** [comment]
yes that bug is letting me want to quit minecraft.

**Comment by skitou** [comment]
> yes that bug is letting me want to quit minecraft.

quit minecraft because of a plugin bug, amazing logic

**Comment by ThePilotNinja** [comment]
> > yes that bug is letting me want to quit minecraft.
> 
> quit minecraft because of a plugin bug, amazing logic

take a joke.
