### ISSUE TITLE
Same names with different letter cases 

### ISSUE THREAD

**Issue by mirolm** [lenis0012/LoginSecurity-2#23]
I runned to issue with same nicks with different case of the letters in them. For example player A is named 'PLAYER' and player B is named 'player'. Player registration is not forced in plugin configuration.

They got different UUID's and can authenticate with different passwords. Issue is when player A logins and player B tries to login too. In this case Player A nick is added to "authList" and when Player B nick is added plugin kicks it with "A player with this name is already online!". Dooh!

This is actually troublesome if some player enters with same nick with different case as some registered player (admin...). Unregistered player with the case letters nick stays in authList (because he never registers...), and registered player can never enter server, because gets kicked.

As i see the code maybe a fix to this is to add "nick + uuid" or only "uuid" to authList, so players get different records in this list when case differs - server gives them other uuid's. This will work with offline servers as server generates different uuid for every nick as with online servers where uuid is never changed and nick can be changed. 

--

I made the changes to my copy of the plugin source and so far it works without problems on the small server i run.

**Comment by lenis0012** [comment]
Please report if present in 2.1
