### ISSUE TITLE
Losing inventory

### ISSUE THREAD

**Issue by HeshamSHY** [lenis0012/LoginSecurity-2#231]
I lost all of my inventory because of this plugin!, even tho I tried /logout and then /login again but it's not working, I tried leaving the server and rejoin and it's not working too!

never gonna use this plugin again if I'm not able to get my stuff back!
![2021-03-21_14 19 26](https://user-images.githubusercontent.com/79906420/111902891-9498f100-8a50-11eb-9345-fd7773b6f58b.png)

**Comment by iyantae245** [comment]
> Hello, I also had this issue so I just disabled the ** hide-inventory: false** option.
> 
> However, this is still a really good plugin.

thanks for the notice.

**Comment by lenis0012** [comment]
@iyantae245 @Odysseum4190 @HeshamSHY This issue should be fixed in version 3.1 which is currently in development. dev builds are available at https://ci.codemc.io/job/lenis0012/job/LoginSecurity/
