### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by jamesorose** [lenis0012/LoginSecurity-2#24]
There's no really easy way to reset a password. In the interim, you can do this via command line.  It would be really nice if this feature was built in. Instead I'm documenting the process of doing it the hard way...

1. You'll need  the UUID of the player. 
2: (assuming default BCRYPT) a new password. Generate one here: https://www.bcrypt-generator.com/

3. access to sqlite. 
sqlite3 plugins/LoginSecurity/users.db
==================================
to reset a person's password to 'password'
==================================
UPDATE users set password="$2a$08$7wBP1so3I/F2OFvJedmrqembWkjey1LjT2b.HnUgg9YMVyAwNgrT6" where unique_user_id="enter_uuid_here_no_punctuation";

==================================
to reset everyone's password to password
==================================
UPDATE users set password="$2a$08$7wBP1so3I/F2OFvJedmrqembWkjey1LjT2b.HnUgg9YMVyAwNgrT6";

.exit

**Comment by lenis0012** [comment]
2.0.13

/lac rmpass <user>
