### ISSUE TITLE
[Question] Does the plugin support version 1.18(.2)?

### ISSUE THREAD

**Issue by Pancakes-Studio** [lenis0012/LoginSecurity-2#270]
Hello, as it is written in the title, my question is that the plugin supports the version 1.18 including the .2? On the page of Spigot it is written that it supports 1.17 in the most recent version.
Thank you for your understanding.

**Comment by Pancakes-Studio** [comment]
I downloaded another plugin that takes the original and says it works in 1.18(.2) (Staff++).

**Comment by lenis0012** [comment]
Hi sorry for the late reply.
I would urge you to test it. i havent kept track of what changed in 1.18 but im pretty sure it shouldn't have broken anything.

If it has, I am willing to fix it.
