### ISSUE TITLE
Absolutely nothing happens after registering. 

### ISSUE THREAD

**Issue by DesolateIntention** [lenis0012/LoginSecurity-2#278]
This plugin is useless. 
After registering, nothing happens. The blindness effect is still present and you can't move, or log in again.

**Comment by DannyAcosta710** [comment]
Do you happen to be in 1.19.1 or later? Chat changes have disabled many of these plugins

**Comment by DesolateIntention** [comment]
I was in 1.19 when the issue occurred. Though in my realization that the plugin had no support I didn't bother to explain any further. It only happened like once or twice before I removed the plugin. Now I'm back, updated to 1.19.2, and it works fine again.
