### ISSUE TITLE
Login Security Locale

### ISSUE THREAD

**Issue by PinoyLifeCraft** [lenis0012/LoginSecurity-2#28]
Hellow :laughing: 
Is it possible to add this in your plugin?
Custom Message!!!
:grey_question:

**Comment by lenis0012** [comment]
planned for 2.1

**Comment by PinoyLifeCraft** [comment]
Yes so plan to add it wow thanks @lenis0012

**Comment by lenis0012** [comment]
Added in 2.1.3
