### ISSUE TITLE
Two databases

### ISSUE THREAD

**Issue by chief-j** [lenis0012/LoginSecurity-2#29]
I have a website and forum they are linked together bridge. If registered by a plug, the data is entered only in one database. Is it possible to write data once in two databases?
For example, transfer logins and passwords on php script that will record in the database

**Comment by Plazmaz** [comment]
Couldn't you just pull from the single database or write a quick script to transfer the database over? It seems like a website's database format is unpredictable and thus with every website being different, transferring credentials would not be a reasonable feature for this plugin

**Comment by chief-j** [comment]
I can write a script but will be delay in copying.
Thank you for the answer

**Comment by lenis0012** [comment]
Please report if present in 2.1
