### ISSUE TITLE
New error in my server.

### ISSUE THREAD

**Issue by KryanThePacifist** [lenis0012/LoginSecurity-2#30]
Hey, so i got this message in my server Console:
java.lang.NullPointerException at com.lenis0012.bukkit.ls.LoginListener$1$1.run(LoginListener.java:75) ~[?:?] at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:53) ~[craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:686) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:361) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:635) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5] at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:539) [craftbukkit-1.9.2.jar:git-Bukkit-22dcde5]
Have Bukkit 1.9.2 Hosted in server.pro
Thanks for your time :D

**Comment by lenis0012** [comment]
is this still happening?

**Comment by lenis0012** [comment]
Please report if present in 2.1
