### ISSUE TITLE
Maven repository

### ISSUE THREAD

**Issue by games647** [lenis0012/LoginSecurity-2#34]
Could you please enable the maven repository in your Jenkins server? I want to be able to use it in one of my projects.

**Comment by lenis0012** [comment]
will setup soon

**Comment by sgdc3** [comment]
@lenis0012 You don't need to setup a nexus repo, just enable the maven repo plugin in jenkins and you get a simple maven repo that stores all the maven artifact compiled by jenkins ;)

**Comment by lenis0012** [comment]
@sgdc3 I dont use maven projects
I generate 2 jars by running maven twice to support both platforms
That makes it a freelance project, which is not supported by that plugin

**Comment by sgdc3** [comment]
What do you mean? Which platforms?

**Comment by lenis0012** [comment]
@sgdc3 bukkit & spigot
they both include a different updater

**Comment by sgdc3** [comment]
............ (worst solution ever)

**Comment by sgdc3** [comment]
1) you want a simple plugin but you added an updater? xD
2) what about modules?
3) maven is designed to solve this issues, if you describe the issue i can help you with it

**Comment by lenis0012** [comment]
@sgdc3 Right now i am running the project under 2 different users that each include a different dependency for the coreresponding platform (bukkit, spigot)

this generates 2 jars (LoginSecurity-Bukkit & LoginSecurity-Spigot)
I do not know of any other way to achieve this, and i have never used modules before.

On your first point, an updater is essential for this plugin in order to ensure players have the latest security patches.

Thanks for your help =)

**Comment by sgdc3** [comment]
what about a common library that detects the server version? and why do you need different updaters? just use one of them on both.

**Comment by lenis0012** [comment]
@sgdc3 bukkit only allows you to use their curse API.
and if i use that on spigot and stop supporting bukkit it will grab updates from a no longer maintained platform.

**Comment by sgdc3** [comment]
Keep using bukkit, and when you'll drop the bukkit page you'll switch to the spigot one.

**Comment by sgdc3** [comment]
It doesn't make any sense to have 2 jars because of a unnecessary and sometimes annoying feature

**Comment by lenis0012** [comment]
@sgdc3 I like the idea of being able to update them seperately.
For instance, i uploaded the alpha builds to bukkit only since it puts no spotlight on experimental builds

**Comment by sgdc3** [comment]
..... how many problems for a stupid thing xD

**Comment by lenis0012** [comment]
@sgdc3 Well, if it ends up being too hard to setup a nexus server ill just go with a single jar.
or figure out how to generate 2.

**Comment by lenis0012** [comment]
Thanks to @sgdc3 its working :)

http://ci.lenis0012.com/plugin/repository/everything/
