### ISSUE TITLE
[Critical] Login does not work - exception

### ISSUE THREAD

**Issue by Vilican** [lenis0012/LoginSecurity-2#38]
I finally got to upgrade from 2.1.1 to 2.1.2 (thanks for the fix of #33, btw). However, there is a critical error preventing anyone to login:

```
16:14:47 [INFO] vilican[/10.38.254.254:57311] logged in with entity id 542 at ([hub]793.9534113022058, 6.742931601724881, -142.96674751684412)
16:14:48 [INFO] Registering IP of vilican
16:14:52 [WARN] Exception in thread "pool-6-thread-1"
16:14:52 [WARN] java.lang.IllegalArgumentException: Name cannot be null
16:14:52 [WARN] 	at org.apache.commons.lang.Validate.notNull(Validate.java:192)
16:14:52 [WARN] 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.getWorld(CraftServer.java:1053)
16:14:52 [WARN] 	at org.bukkit.Bukkit.getWorld(Bukkit.java:517)
16:14:52 [WARN] 	at com.lenis0012.bukkit.loginsecurity.storage.PlayerLocation.asLocation(PlayerLocation.java:46)
16:14:52 [WARN] 	at com.lenis0012.bukkit.loginsecurity.session.AuthAction.rehabPlayer(AuthAction.java:65)
16:14:52 [WARN] 	at com.lenis0012.bukkit.loginsecurity.session.action.LoginAction.run(LoginAction.java:23)
16:14:52 [WARN] 	at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:159)
16:14:52 [WARN] 	at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$2.run(PlayerSession.java:133)
16:14:52 [WARN] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
16:14:52 [WARN] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
16:14:52 [WARN] 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by lenis0012** [comment]
it seems your login locations are invalid.
I will fix it asap :)

**Comment by lenis0012** [comment]
@Vilican Please test and report whether or not it was fixed in latest dev build :)

**Comment by HashSploit** [comment]
Thanks for opening this @Vilican . I am experiencing a similar issue. Also @lenis0012 this is shown when a user logins for the 2nd time right after connecting:


> [19:19:09 INFO]: hashsploit[/99.162.65.228:56700] logged in with entity id 419 at ([world]-81.0, 64.0, 245.0)
> [19:19:10 WARN]: Exception in thread "pool-6-thread-1" 
> [19:19:10 WARN]: javax.persistence.PersistenceException: ERROR executing DML bindLog[] error[[SQLITE_CONSTRAINT]  Abort due to constraint violation (PRIMARY KEY must be unique)]
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:116)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.insert(DmlBeanPersister.java:76)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersistExecute.executeInsertBean(DefaultPersistExecute.java:91)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeNow(PersistRequestBean.java:500)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.core.PersistRequestBean.executeOrQueue(PersistRequestBean.java:530)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.insert(DefaultPersister.java:406)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaInsert(DefaultPersister.java:377)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveVanillaRecurse(DefaultPersister.java:361)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:308)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveAssocOne(DefaultPersister.java:1229)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.update(DefaultPersister.java:432)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveEnhanced(DefaultPersister.java:343)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.saveRecurse(DefaultPersister.java:315)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.DefaultPersister.save(DefaultPersister.java:282)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1629)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.core.DefaultServer.save(DefaultServer.java:1619)
> [19:19:10 WARN]:        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession$1.run(PlayerSession.java:48)
> [19:19:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> [19:19:10 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> [19:19:10 WARN]:        at java.lang.Thread.run(Thread.java:745)
> [19:19:10 WARN]: Caused by: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (PRIMARY KEY must be unique)
> [19:19:10 WARN]:        at org.sqlite.DB.newSQLException(DB.java:383)
> [19:19:10 WARN]:        at org.sqlite.DB.newSQLException(DB.java:387)
> [19:19:10 WARN]:        at org.sqlite.DB.execute(DB.java:342)
> [19:19:10 WARN]:        at org.sqlite.DB.executeUpdate(DB.java:363)
> [19:19:10 WARN]:        at org.sqlite.PrepStmt.executeUpdate(PrepStmt.java:85)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.lib.sql.ExtendedPreparedStatement.executeUpdate(ExtendedPreparedStatement.java:164)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.type.DataBind.executeUpdate(DataBind.java:74)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.dml.InsertHandler.execute(InsertHandler.java:158)
> [19:19:10 WARN]:        at com.avaje.ebeaninternal.server.persist.dml.DmlBeanPersister.execute(DmlBeanPersister.java:105)
> [19:19:10 WARN]:        ... 19 more

**Comment by Vilican** [comment]
Thanks, it is working now.

**Comment by lenis0012** [comment]
@HashSploit 
Please post the full log using pastebin.

This issue happens the 2nd time the player logs in or the 2nd time they use /login?

**Comment by HashSploit** [comment]
@lenis0012 
Sorry for the very late reply, thanks for looking into this and making a great plugin.

I should also mention I'm using [paper](https://paper.readthedocs.io/en/paper-1.10/), which is a fork of spigot.

https://github.com/PaperMC/Paper

I hoped to make it a bit easier to help fix this issue by downloading [this](http://ci.lenis0012.com/job/LoginSecurity%202/) version and deleting the previous LoginSecurity folder in plugins to get a fresh start, and here's the latest log from init:

http://pastebin.com/XY5dUJFY

The previous player login (on the command "/login" via player) issue appears to be fixed.
But there's another issue I am having, I set the following value in LoginSecurity/config.yml:

\#Temporarily login location until player has logged in.
  \#Available options: DEFAULT, SPAWN, RANDOM
  location: SPAWN

However even after the player logs in they remain at spawn, would this be a plugin conflict? or is there a way to make sure your plugin LoginSecurity has the highest priority for setting the players current location?

Plugins that may be in conflict:
- essentials
- essentials-spawn
- [random spawn](http://dev.bukkit.org/bukkit-plugins/random-spawn/)

I'm basically just trying to make sure players randomly spawn on first join or on death, if they have  bed set, that will be their spawn but not login location, their login location should always be either the world spawn or something like that.

What is your recommendation?

**Comment by nIKiTaaaaaaa-coder** [comment]
I have CraftBukkit (last version) and the last version of LoginSecurity, so basically I have the same problem.
```
java.lang.IllegalArgumentException: name cannot be null
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.getPlayer(CraftServer.java:559) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3859-Bukkit-f70a7b6]
        at org.bukkit.Bukkit.getPlayer(Bukkit.java:611) ~[bukkit-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.getPlayer(PlayerSession.java:131) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.session.AuthAction.rehabPlayer(AuthAction.java:49) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.session.action.LoginAction.run(LoginAction.java:27) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.session.PlayerSession.performAction(PlayerSession.java:169) ~[?:?]
        at com.lenis0012.bukkit.loginsecurity.commands.CommandLogin.lambda$execute$1(CommandLogin.java:67) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:77) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3859-Bukkit-f70a7b6]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[craftbukkit-1.20.1-R0.1-SNAPSHOT.jar:3859-Bukkit-f70a7b6]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
I don't have any hosting, it's just hosted on my own server and I can't login.

**Comment by nIKiTaaaaaaa-coder** [comment]
I strongly want to use this plugin, but for now I am using other plugins for authentication.
