### ISSUE TITLE
Add /lac update, /lac reload ,/lac changepass and /myemail and LoginSecurity is the most awesome LoginPlugin forever

### ISSUE THREAD

**Issue by Tzzzt123** [lenis0012/LoginSecurity-2#42]
Can you add /lac update command so i can update without needing to download LoginSecurity again
and /lac reload to reload the config without restart and /lac changepass <player> <Newpw> to change player's passwords
and /myemail <email-adress> to recover player passwords
THANKS and regards: Tzzzt123

- [x] /lac update
- [x] /lac reload
- [x] /lac changepass

**Comment by lenis0012** [comment]
@Tzzzt123 Currently workgin on translations.
I will add these features once im done with that.

**Comment by Tzzzt123** [comment]
and /lac rmpass still dont work

**Comment by lenis0012** [comment]
@Tzzzt123 any errors?

**Comment by Tzzzt123** [comment]
When i come online with my secondary account it says *Please login using "/login <password>".*
And when i am in the console and i type /lac rmpass (name-of-my-secondary-account) it answers:
*No player with that name has been registered!*

**Comment by Tzzzt123** [comment]
(/login [ pass word ])

**Comment by Plazmaz** [comment]
@Tzzzt123 is the capitalization the same?

**Comment by Tzzzt123** [comment]
@Plazmaz the text part "[ pass word ]" should represent the password login message

**Comment by Plazmaz** [comment]
@Tzzzt123 I was referring to the usernames. Was the case the same in the usernames?

**Comment by Tzzzt123** [comment]
Yes @Plazmaz

**Comment by lenis0012** [comment]
/lac udpate
was added in 2.1.3

/lac rmpass
was fixed in 2.1.3

**Comment by Tzzzt123** [comment]
/lac rmpass still don't work (same message)

**Comment by Tzzzt123** [comment]
so that is why you should add /lac changepass so this message can't have any sense anymore!

**Comment by Tzzzt123** [comment]
@lenis0012 so when do you add /lac changepass

**Comment by Tzzzt123** [comment]
add /lac changepass plss

**Comment by Tzzzt123** [comment]
@lenis0012 thanks

**Comment by Tzzzt123** [comment]
@lenis0012 this issue is still open.

**Comment by lenis0012** [comment]
@Tzzzt123 I know, busy at the moment tho.

**Comment by Tzzzt123** [comment]
@lenis0012 ok

**Comment by Tzzzt123** [comment]
@lenis0012 lenis u finished with translations right?
then pls do this updates...

**Comment by sgdc3** [comment]
> LoginSecurity is the most awesome LoginPlugin forever

Nope :P

**Comment by Tzzzt123** [comment]
@sgdc3 it is lol

**Comment by sgdc3** [comment]
nuuu authameee is betterrr :P

**Comment by Tzzzt123** [comment]
@sgdc3 advertising warn (1.)

**Comment by lenis0012** [comment]
@sgdc3 baaan ;d

**Comment by Tzzzt123** [comment]
:)

**Comment by lenis0012** [comment]
@Tzzzt123 Added the reload command.
Will be available in 2.2

**Comment by lenis0012** [comment]
@Tzzzt123 so, what about /myemail?

**Comment by lenis0012** [comment]
Going to consider this "Implemented"

**Comment by Tzzzt123** [comment]
ok
"/myemail <email>" should be to give the email adress containing the pass so if you forget the pass it sends it to your email to copy paste
Thanks
@lenis0012

**Comment by lenis0012** [comment]
@Tzzzt123 We don't store the player's password in plain text.
So we cannot send to them.

Same reason why requesting a password reset on website gives you a url to reset it rather than send you your password.
