### ISSUE TITLE
[Application] Translations

### ISSUE THREAD

**Issue by Tzzzt123** [lenis0012/LoginSecurity-2#43]
Dear lenis0012,
can i help with the translation of LoginSecurity? I can speak french and german! So if you need translated strings, tell me!
Regards Tzzzt123

**Comment by lenis0012** [comment]
https://github.com/lenis0012/LoginSecurity-2/blob/master/src/main/resources/lang/en_us.json

you can make a translated version for the upcoming update.
I will make a github project where you can submit translatiosn very soon.

french is "fr_fr" and german is "de_de"
You can start translating if you want, and submit the files when the translation project is up.
Somes notes:

The first argument (ex. "generalNotAuthenticated") should not be translated.
The % arguments are replaces and should not be translated (ex. %min%)
You can't use the " character in your messages

I recommend using http://www.jsoneditoronline.org/

**Comment by Tzzzt123** [comment]
and special chars?

**Comment by lenis0012** [comment]
@Tzzzt123 any unicode character should be fine

**Comment by Tzzzt123** [comment]
ok thanks

**Comment by sgdc3** [comment]
@lenis0012 Gitter, gitter, gitter, gitter.... *returns into the shadows*

**Comment by lenis0012** [comment]
@sgdc3 lol <3

**Comment by Tzzzt123** [comment]
@lenis0012 what should i put in the branch authors? just lenis or also the translator's name?
Thanks Tzzzt123

**Comment by Tzzzt123** [comment]
translations done, tell me when you need them please

**Comment by lenis0012** [comment]
@Tzzzt123 Could you PR them to https://github.com/lenis0012/Translations/tree/master

You can click on https://gyazo.com/607f72f37178238c054b7ec310c4c5e6 "create new file"
and paste your translations in

**Comment by Tzzzt123** [comment]
I put them on a own repository LINK: https://github.com/Tzzzt123/Translations
Regards Tzzzt123

**Comment by lenis0012** [comment]
@Tzzzt123 read it

**Comment by Tzzzt123** [comment]
ok, thanks done

**Comment by Plazmaz** [comment]
@lenis0012 is currently offline for a few days, he should be back at the end of this week.
