### ISSUE TITLE
Translation :3

### ISSUE THREAD

**Issue by Small-Ku** [lenis0012/LoginSecurity-2#44]
There is Chinese(Taiwan) and Chinese(Hong Kong)
TW:http://pastebin.com/2UxQeKwi
HK:http://pastebin.com/wFhQDsSw
[zh-tw]Chinese(Taiwan) is the formal Traditional Chinese.
[zh-yue][zh-hk]Chinese(Hong Kong) is the writing Cantonese which is the most popular language in Hong Kong.
Hope this useful for you :3

**Comment by Plazmaz** [comment]
@Small-Ku Please see https://github.com/lenis0012/Translations/wiki/Contribute. Your translations, while in the correct format, should be submitted as a pull request to https://github.com/lenis0012/Translations. If you'd like I could do that for you.
