### ISSUE TITLE
汉化文件，帮助中国玩家。

### ISSUE THREAD

**Issue by 911061873** [lenis0012/LoginSecurity-2#45]
{
  "localizedName": "Chinese",
  "pluginVersion": "2.1.3",
  "authors": "lenis 汉化BY：n233333",
  "generalNotAuthenticated": "您未注册或已登录！",
  "generalNotLoggedIn": "您目前未登录！",
  "generalPasswordLength": "密码位数必须在 %min% 和 %max% 之间！",
  "generalUnknownHash": "您的帐户使用了一个未知的加密算法，请联系管理员。",
  "loginTriesExceeded": "超过最大尝试登录次数： %max% ",
  "loginFail": "登录失败！密码无效。",
  "loginSuccess": "登录成功。",
  "changeFail": "更改失败，密码错误！",
  "changeSuccess": "密码更改成功！",
  "logoutFail": "退出失败，错误： %error% ",
  "logoutSuccess": "您已成功注销！",
  "registerAlready": "您已在该帐户下注册！",
  "registerCaptcha": "请在聊天窗口中输入验证码！",
  "registerSuccess": "已成功注册，现在以登录。",
  "commandError": "执行命令时出错： %error%",
  "commandUnknown": "未知命令！使用 %cmd% 查看帮助！",
  "commandArguments": "参数不正确！ 使用 %cmd% 来查看帮助！",
  "lacHelp": "查看帮助。",
  "lacRmpass": "删除用户的密码",
  "lacRmpassArgs": "<username>",
  "lacNotRegistered": "没有玩家用那个用户名注册！",
  "lacResetPlayer": "重置玩家账户成功！",
  "lacImport": "从其他数据库导入数据！",
  "lacImportArgs": "<source> [args]",
  "lacUnknownSource": "未知的数据类型，请检查看维基获取帮助！",
  "lacImportFailed": "无法执行导入，请检查日志！",
  "sessionContinue": "您在 %sec% 秒前的登录还没有断开。",
  "messageLogin": "请使用 /login <密码> 登录！",
  "messageRegister": "请使用 /register <密码> 注册。",
  "errorRefreshProfile": "您的账户被第三方修改，请重新加入。",
  "errorNotRegistered": "用户未注册！",
  "kickAlreadyOnline": "这个玩家在线！",
  "kickUsernameChars": "您的用户名包含非法字符！",
  "kickUsernameLength": "您的用户名太长或太短，应该在 %min% 位和 %max% 位之间。",
  "kickTimeOut": "登录超时！"
  //汉化BY：n233333 QQ911061873
}

**Comment by Plazmaz** [comment]
@911061873 Please see https://github.com/lenis0012/Translations/wiki/Contribute. Your translations, while in the correct format, should be submitted as a pull request to https://github.com/lenis0012/Translations.

**Comment by 911061873** [comment]
Right now?

**Comment by 911061873** [comment]
@Plazmaz  Right now?

**Comment by Plazmaz** [comment]
@911061873 sorry what?

**Comment by 911061873** [comment]
I Can't use GIT . can you help  me ? I want add the language file.

**Comment by 911061873** [comment]
@Plazmaz

**Comment by Plazmaz** [comment]
@911061873 if you follow the contribution tutorial I linked, you shouldn't need to use Git.

**Comment by 911061873** [comment]
NO !  I Can't

**Comment by Plazmaz** [comment]
@911061873 What do you mean?

**Comment by 911061873** [comment]
OK.I'll try
