### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by Vilican** [lenis0012/LoginSecurity-2#53]
LoginSecurity will strip special characters like ěščřžýááíé from translations.
Applies only to console.

**Comment by Vilican** [comment]
Applies only to console.

**Comment by Vilican** [comment]
Also, is this for debug?

`14:42:56 [INFO] [LoginSecurity] FUCK ME
14:42:56 [INFO] [LoginSecurity] FUCK ME TWICE`

**Comment by games647** [comment]
@Vilican I think the last one comes from AutoIn

**Comment by sgdc3** [comment]
lol

**Comment by games647** [comment]
>@Vilican I think the last one comes from AutoIn

I was wrong the message in AutoIn is different. This just sounds like LoginSecurity debug code for loading a different language file.

**Comment by lenis0012** [comment]
Yea that debug message seems like a bug.
No idea why it would say that.

it must be parsing messages incorrectly for sure...

**Comment by Plazmaz** [comment]
This one deserves to be immortalized in history.... https://www.reddit.com/r/ProgrammerHumor/comments/4tc2ka/so_my_friend_accidentally_let_some_debug_messages/

**Comment by axynos** [comment]
this is brilliant

**Comment by MohammadAlHajj** [comment]
@Plazmaz thanks for the nice morning gift

**Comment by Plazmaz** [comment]
@lenis0012 if you're planning on wontfixing, you should probably close the issue
