### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by zuhir** [lenis0012/LoginSecurity-2#54]
`{
  "localizedName": "Español (MX)",
  "pluginVersion": "2.1.3",
  "authors": "lenis, Plazmaz",
  "generalNotAuthenticated": "No estas registrado o ya has iniciado sesion!",
  "generalNotLoggedIn": "No has iniciado sesion!",
  "generalPasswordLength": "La clave debe tener entre %min% y %max% letras y/o numeros!",
  "generalUnknownHash": "Tu cuenta utiliza un algoritmo desconocido, por favor reporta esto con un administrador.",
  "loginTriesExceeded": "Has superado el limite de intentos (%max%)",
  "loginFail": "Ha fallado el inicio de sesion! La clave introducida es incorrecta.",
  "loginSuccess": "Sesion iniciada correctamente.",
  "changeFail": "No se pudo modificar, clave incorrecta!",
  "changeSuccess": "Clave modificada correctamente!",
  "logoutFail": "No se pudo cerrar sesion! %error%",
  "logoutSuccess": "Sesion cerrada correctamente!",
  "registerAlready": "Esta cuenta ya esta registrada!",
  "registerCaptcha": "Por favor introduce el captcha que aparece en el mapa por el chat!",
  "registerSuccess": "Te has registrado correctamente.",
  "commandError": "Ha ocurrido un error al ejecutar el comando: %error%",
  "commandUnknown": "Comando desconocido! Usa %cmd% para obtener ayuda.",
  "commandArguments": "Faltan argumentos! Usa %cmd% para obtener ayuda.",
  "lacHelp": "Muestra esta pagina de ayuda.",
  "lacRmpass": "Borra la clave de un jugador.",
  "lacRmpassArgs": " <jugador>",
  "lacNotRegistered": "No hay ningun jugador registrado con ese nombre!",
  "lacResetPlayer": "Cuenta reiniciada correctamente!",
  "lacImport": "Importar desde otra base de datos.",
  "lacImportArgs": " <source> [args]",
  "lacUnknownSource": "Tipo de base de datos desconocido, por favor mira la wiki!",
  "lacImportFailed": "No se pudo importar, por favor mira el log!",
  "sessionContinue": "Tu ultimo inicio de sesion se continuo a partir de %sec% seconds ago.",
  "messageLogin": "Por favor inicia sesion usando /login <clave>",
  "messageRegister": "Por favor registrate usando /register <clave>",
  "errorRefreshProfile": "Tu cuenta ha sido modificada por staff, por favor vuelve a entrar!",
  "errorNotRegistered": "El jugador no se ha registrado!",
  "kickAlreadyOnline": "Ya hay un jugador con tu nombre en el servidor!",
  "kickUsernameChars": "Tu nombre contiene caracteres ilegales!",
  "kickUsernameLength": "Tu nombres es muy largo/corto! (%min% - %max% caracteres)",
  "kickTimeOut": "Tiempo de inicio de sesion agotado!"
}`

**Comment by lenis0012** [comment]
https://github.com/lenis0012/Translations/wiki/Contribute

Please follow the isnstructions on there

**Comment by zuhir** [comment]
xDD sorry, i dont use Github

**Comment by lenis0012** [comment]
@zuhir no problem. thew instructions are easy to follow :)

**Comment by Plazmaz** [comment]
Author should also be "zuhir"
