### ISSUE TITLE
[QUESTION] Migrating to mysql.

### ISSUE THREAD

**Issue by dyanakiev** [lenis0012/LoginSecurity-2#57]
Is possible to migrate existing LoginSecurity-2 file database to mysql?

Thanks!

**Comment by lenis0012** [comment]
I thought it was.
But i mjay have forgotten to implement it.
Will do it for 2.1.5, but ill double check

**Comment by dyanakiev** [comment]
Ok nice, your build server is down :cry:

**Comment by lenis0012** [comment]
@dyanakiev Its back up

**Comment by dyanakiev** [comment]
@lenis0012 Any news for sqlite to mysql migrating?

**Comment by dyanakiev** [comment]
bump :crying_cat_face:

**Comment by lenis0012** [comment]
@dyanakiev 2.2
