### ISSUE TITLE
Lost inventory

### ISSUE THREAD

**Issue by plachta11b** [lenis0012/LoginSecurity-2#59]
All players who log out and log in lost all their items from inventory.

Download LoginSecurity v2.1.4 (Jul 18, 2016)
I have fresh install (i remove old config and setup new database)
I configure only mySQL if I remember
Remove inventory for all players who logout for time longer then 1 minute (limit for password less login)
My server run spigot-1.10.2-R0.1-SNAPSHOT
hide-inventory: true -> hide-inventory: false fix this issue

**Comment by danny8376** [comment]
If VARCHAR of your SQL server is limited to 256 chars, you'll need to manually to change type of contents field of ls_inventories table from VARCHAR to TEXT/MEDIUMTEXT.

**Comment by lenis0012** [comment]
@danny8376 that actually helped me...

**Comment by Tzzzt123** [comment]
I also had this problem

**Comment by lenis0012** [comment]
@Tzzzt123 the issue should be resolved in the new version. (2.1.5)

@danny8376 you helped me out, i completely forgot to set the data length for the inventory model.
thanks <3
