### ISSUE TITLE
API handling for login event

### ISSUE THREAD

**Issue by HashSploit** [lenis0012/LoginSecurity-2#62]
Can you point me into the right direction on how to get a boolean value if a Player has logged in or not (not via event call, but by passing in a Player object and getting a boolean back from your plugin)? In my queue plugin I first need to check if a player is logged in or not. If they are, I add that player to my ArrayList<Player>. (This way the authentication plugin is run on a separate minimalistic server along with the queue built in. For example: If the player disconnects from the queue server and connects again, they are automatically logged back in via your plugin, and then added back into the que unless they do /logout or their login session expires, then I am using your event listener to remove that player from the queue). Thanks!

**Comment by lenis0012** [comment]
Sorry for my late response

you would do something like:
`final PlayerSession session = LoginSecurity.getSessionManager().getPlayerSession(player);
if(session.isAuthorized())`

**Comment by HashSploit** [comment]
Thanks!
