### ISSUE TITLE
[REQ] | MySQL support

### ISSUE THREAD

**Issue by TrademarkTM** [lenis0012/LoginSecurity-2#63]
Hello!
This is a great plugin, really great with translations (the colors are glitched in some of them, maybe you should take a look), but anyways, I need MySQL to make it run faster.

Could you add it?
Thanks!

**Comment by dyanakiev** [comment]
There is mysql rofl :D

**Comment by TrademarkTM** [comment]
Oh, it's not in the config file, but in database.yml xD
Thread closed.

**Comment by lenis0012** [comment]
Lol =)

There are some issues with hide-inventory and MySQL, so i recommend you keep the hide-inventory setting disabled until 2.0.5 is released if you're going to use it @TrademarkTM
