### ISSUE TITLE
Add password verification on registration

### ISSUE THREAD

**Issue by JugadorON** [lenis0012/LoginSecurity-2#67]
https://dev.bukkit.org/bukkit-plugins/loginsecurity/

Adds dual password please!!! Login and register.

**Comment by TrademarkTM** [comment]
Yeah, that's quite useful.
Sometimes I type my password wrongly and I cannot login anymore.

**Comment by Plazmaz** [comment]
What do you mean by this? Multiple passwords for the same account?

**Comment by lenis0012** [comment]
@Plazmaz /register <password> <passwordAgain>

**Comment by Tzzzt123** [comment]
gud
