### ISSUE TITLE
Login Security Locale

### ISSUE THREAD

**Issue by PinoyLifeCraft** [lenis0012/LoginSecurity-2#68]
Hello Owner I made a file in Login Security Folder "en_us.json"
I change the login message to &f&l[&4&lLogin&f&l] &cPlease do /login <password>
And it's not working :disappointed: so I delete the en_us.json file and Stop the server followed by Start
What happened the login message Isn't working ... Here is the ScreenShot
![2016-10-31_06 47 21](https://cloud.githubusercontent.com/assets/13610530/19840661/025553f6-9f36-11e6-85f7-14fc3d5942c8.png)
That Screenshot is when I join and there is no message to say Please log in using /login bla bla bla
But if I do /login password this is the next message :label: 
![2016-10-31_06 47 33](https://cloud.githubusercontent.com/assets/13610530/19840675/6a5062fc-9f36-11e6-8dc3-4498b2307e65.png)

**Comment by Plazmaz** [comment]
I don't believe modification of the language files is currently supported.

**Comment by PinoyLifeCraft** [comment]
Hello Plugin's owner Could I request to change the file type or not then please fix it please :+1:

**Comment by lenis0012** [comment]
@PinoyLifeCraft @Plazmaz You can install a custom language file, by adding it to your loginsecurity folder and using the given name in the configuration.

but, you are not suppost to change the formatting/colors of the messages.
