### ISSUE TITLE
Better username and password validation

### ISSUE THREAD

**Issue by mirolm** [lenis0012/LoginSecurity-2#74]
Usernames and passwords can be validated with regex:

 - for username regex can be "^\\w{3,16}$"
 - for passwords "^(?=.*[a-zA-Z])(?=.*([0-9]|[!@#\\$%\\^&\\*])).{6,}+$"

Useful regex test site is https://regex101.com/ :D

Password validation can be optional and there can be a message to warn players that their password is weak and they should change it. Also there can be an optional functionality to force password change if password is weak.

**Comment by lenis0012** [comment]
I agree that the passwords would be a cool feature.
As for the username, the min and max length would ideally by configurable, as it is right now.

But yeah, i like the password regex.

**Comment by mirolm** [comment]
Username min and max in regex is same length as mojang uses. I forced this regex, because if username is not validated plugins that fetch skins for offline servers do not work so good.

**Comment by lenis0012** [comment]
maybe so, that's wy the default is set to 3 <> 16

but if server owners want to allow shorter names, or limit lame length to less than 16, they can do so.

**Comment by lenis0012** [comment]
@mirolm how about implementing https://github.com/nulab/zxcvbn4j ?

**Comment by mirolm** [comment]
It can work - it seems like a good one.
