### ISSUE TITLE
Add short aliases to plugin commands

### ISSUE THREAD

**Issue by mirolm** [lenis0012/LoginSecurity-2#75]
I noticed alot of players try to use short commands maybe because in other plugins they are implemented:

/login --> /l, /log
/register --> /reg
/changepass --> /changepassword, /cp

There was even players that messaged me and asked why they can not use /l instead of /login for example.

**Comment by lenis0012** [comment]
https://github.com/lenis0012/LoginSecurity-2/blob/master/src/main/java/com/lenis0012/bukkit/loginsecurity/LoginSecurityConfig.java#L79

https://github.com/lenis0012/LoginSecurity-2/blob/master/src/main/java/com/lenis0012/bukkit/loginsecurity/modules/general/PlayerListener.java#L203

does that seem sufficient?

**Comment by lenis0012** [comment]
@mirolm that's because i wanted it to be configurable :P

**Comment by Tzzzt123** [comment]
look in config.yml
btw it doesn't work lenis please verify thanks
