### ISSUE TITLE
Ebean gets deprecated in spigot

### ISSUE THREAD

**Issue by mirolm** [lenis0012/LoginSecurity-2#76]
In the following commit in spigot/bukkit repository ebean gets deprecated. It will be completely removed in 1.12.

[d991ef4bc922b6d3fd68e2e48d88545654b57eb8](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/commits/d991ef4bc922b6d3fd68e2e48d88545654b57eb8)

**Comment by lenis0012** [comment]
damn :'s

**Comment by lenis0012** [comment]
EbeanORM usage has been removed as of version 3.0.0
