### ISSUE TITLE
Changing login location does not work.

### ISSUE THREAD

**Issue by agustaf9** [lenis0012/LoginSecurity-2#77]
Changing Login Location in the config file to RANDOM does nothing when the user logs in, they are still at the default location. Using the SPAWN option they are teleported to spawn but underground and then left there after login.

I am using spigot-1.11 and LS 2.1.7 Snapshot (Did the same with earlier versions as well.)

**Comment by lenis0012** [comment]
i know why this is happening.
ill fix it soon

**Comment by nelmaster** [comment]
Yeah I hope this fix be ready soon

thank @Lenis0012

**Comment by lenis0012** [comment]
Removing this issue, as it should be fixed in the latest version.
Please create a new issue if it still happens
