### ISSUE TITLE
UUID mismatch when username contains capital letter

### ISSUE THREAD

**Issue by tantalate** [lenis0012/LoginSecurity-2#78]
LoginSecurity will generate UUID with lower-cased username. Is this intended?

The UUID generated by Bukkit is not the same, e.g.
Bukkit's Log:
[13:38:14 INFO]: UUID of player Tomas is c55f5276-9794-3aa9-bb04-9ebc88097d07

where LS will generate UUID for Tomas as `ba8d1ab7-fe76-3748-ae67-ee71483ea4e3' (for tomas).

I found this tricky when I tried to genreate UUID from outside of bukkit. Should I keep using lower case everywhere?

**Comment by lenis0012** [comment]
This is intentional.

Because some plugins treat players with different caps as the same player.
So for offline-mode servers, we base it of the lower case name so that John and john are treated as the same person.
