### ISSUE TITLE
Should i make a toDo list at the Wiki collecting all toDo in the issues?

### ISSUE THREAD

**Issue by Tzzzt123** [lenis0012/LoginSecurity-2#80]
Lenis or Plazmaz tell me if i should do so

**Comment by lenis0012** [comment]
https://github.com/lenis0012/LoginSecurity-2/milestone/1 =)

**Comment by lenis0012** [comment]
you can reference that if you want, but it'd be silly to maintain 2 lists

**Comment by Tzzzt123** [comment]
ok

**Comment by Tzzzt123** [comment]
when will you make login security version 2.2? and please don't change the database name again?
@lenis0012

**Comment by lenis0012** [comment]
@Tzzzt123 Not planning on changing the database/table names.
Just going to replace the database engine to guarantee support for 1.12.
Shouldn't be any changes in the structure of the db though.

**Comment by Tzzzt123** [comment]
Closing this thread because it's done
