### ISSUE TITLE
Waiting for 2.2!!!

### ISSUE THREAD

**Issue by swordin** [lenis0012/LoginSecurity-2#84]
We're waiting for update! Currently /reg does not work properly, so we lose many players who do not read the invite message but type "/reg" and get an error and go away. Please, correct the bug!

**Comment by lenis0012** [comment]
It was fixed in 2.2, dev builds of this version will become available soon.

**Comment by swordin** [comment]
Thank you very much! It sounds great!

And will it become available to download on https://dev.bukkit.org/projects/?

**Comment by swordin** [comment]
> It was fixed in 2.2, dev builds of this version will become available soon.

So when it become available?

**Comment by swordin** [comment]
So when??? 

A year has passed (((
