### ISSUE TITLE
Please don't change the database in 2.2

### ISSUE THREAD

**Issue by Tzzzt123** [lenis0012/LoginSecurity-2#88]
Please don't change the database in 2.2 because it would be very annoying to transfer the files.
Thanks Tzzzt123
@lenis0012 please mind that.

**Comment by lenis0012** [comment]
@Tzzzt123 I will change the database driver.
I will try my best at not changing the file format though, that way nothing will have to be migrated

**Comment by Tzzzt123** [comment]
thanks @lenis0012

**Comment by Tzzzt123** [comment]
Good, closing this thread for being accepted...
