### ISSUE TITLE
Feature request: the maintenance mode.

### ISSUE THREAD

**Issue by swordin** [lenis0012/LoginSecurity-2#95]
It would be great to have a feature to turn on the maintenance mode when only admins could enter the server.

Thank you.

**Comment by Tzzzt123** [comment]
Simply enable whitelist and add your admins to this whitelist.

**Comment by swordin** [comment]
Using the whitelists is inconvenient -- does it not requires a server reboot?

**Comment by Tzzzt123** [comment]
no @swordin 
do /whitelist on and /whitelist add <admin1> and /whitelist add <admin2>...

**Comment by Tzzzt123** [comment]
no need2reboot

**Comment by swordin** [comment]
I see, you're right, thank you!

**Comment by Tzzzt123** [comment]
np @swordin
