### ISSUE TITLE
When will 2.2 official version be available?

### ISSUE THREAD

**Issue by Tzzzt123** [lenis0012/LoginSecurity-2#98]
@lenis0012 please tell me

**Comment by lenis0012** [comment]
@Tzzzt123 This weekend im hopeing to refactor the database engine.
I plan to release a beta version in early april, and the full version mid april

**Comment by Tzzzt123** [comment]
@lenis0012 and will you need to add translation strings?
Tell me so i can update my translation when 2.2 comes out.

**Comment by lenis0012** [comment]
@Tzzzt123 First beta

**Comment by Tzzzt123** [comment]
ok

**Comment by Tzzzt123** [comment]
Closing this issue because it's solved
