### ISSUE TITLE
KEEP NAUSEA

### ISSUE THREAD

**Issue by yasons** [lenis0012/LoginSecurity-2#99]
I got a problem when login.

register password was successful, but couldn't walk and kept getting nausea effect.
Spigot version 1.11
Plugin version 2.1.6

Picture:
![login problem 1](https://cloud.githubusercontent.com/assets/25345538/24910377/c7eb30dc-1ef1-11e7-8e81-ef17af1384c2.png)

![login problem 2](https://cloud.githubusercontent.com/assets/25345538/24910402/d8df892e-1ef1-11e7-9e96-66953141fdf6.png)

**Comment by Tzzzt123** [comment]
try doing /effect Artire clear

**Comment by lenis0012** [comment]
NAUSEA ?

What version are you using? o.0
that feature was removed all together a long time ago.

**Comment by yasons** [comment]
Problem Solved..!!

I just check and found another account security plugin. Sorry and thanks so much for your response.

CASE CLOSED

**Comment by lenis0012** [comment]
@yasons </3
Why didn't you update the plugin? out of curiosity?
